defaults:
    - task: frag
    - model: ssg
    - task_model: ${defaults.0.task}-${defaults.1.model}

hydra:
  run:
    dir: test_20220223 #結果フォルダの名前

gpus:
    - 0

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
